package com.don.tokenomy.utils

class ConstantsFile {
    companion object{
       const val  ten_btc = "TEN/BTC"
       const val  eth_btc = "ETH/BTC"
       const val  trx_btc = "TRX/BTC"
       const val  lrc_btc = "LRC/BTC"
       const val  vex_btc = "VEX/BTC"
       const val  ltc_btc = "LTC/BTC"
       const val  bchabc_btc = "BCHABC/BTC"
       const val  bchsv_btc = "BCHSV/BTC"
       const val  etc_btc = "ETC/BTC"
       const val  ont_btc = "ONT/BTC"
       const val  six_btc = "SIX/BTC"
       const val  xlm_btc = "XLM/BTC"
       const val  pxg_btc = "PXG/BTC"
       const val  lyfe_btc = "LYFE/BTC"
       const val  btt_btc = "BTT/BTC"
       const val  zec_btc = "ZEC/BTC"
       const val  hnst_btc = "HNST/BTC"
       const val  swipe_btc = "SWIPE/BTC"
       const val  perl_btc   = "PERL/BTC"
       const val  xmr_btc   = "XMR/BTC"
       const val  eos_btc   = "EOS/BTC"
       const val  ten_eth   = "TEN/ETH"
       const val  trx_eth   = "TRX/ETH"
       const val  hart_eth   = "HART/ETH"
       const val  inx_eth   = "INX/ETH"
       const val  vex_ten   = "VEX/TEN"
       const val  six_ten   = "SIX/TEN"
       const val  ten_usdt   = "TEN/USDT"
       const val  btc_usdt   = "TEN/USDT"
       const val  eth_usdt   = "TEN/USDT"
       const val  fgram_usdt   = "TEN/USDT"
       const val  btc_idk   = "BTC/IDK"
       const val  usdt_idk   = "USDT/IDK"
       const val  perl_idk   = "PERL/IDK"
       const val  fgram_idk   = "FGRAM/IDK"
       const val  scc_idk   = "SCC/IDK"
    }
}